# Generated by Django 3.1.5 on 2021-02-03 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='frist_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile',
            new_name='profile_image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='recevie_newsletter',
            new_name='receive_newsletter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='adddress',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
