# Generated by Django 3.1.5 on 2021-02-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('car_brand', models.CharField(max_length=100)),
                ('round_finishing_time', models.IntegerField(default=0)),
            ],
        ),
    ]
